spring:
  application:
    name: "application-service"

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

properties-example:
  greeting: "Hello "
  default-value: "Profile 2"