server:
  port: 3000
  servlet:
    context-path: "/spring-cloud"

spring:
  application:
    name: "application-service"

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

properties-example:
  greeting: "Hello "
  default-value: "Profile 1"