server:
  port: 3000
  servlet:
    context-path: "/spring-cloud"

spring:
  application:
    name: "default-configuration"


properties-example:
  greeting: "Hello "
  default-value: "Default Profile"